
name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint code and docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com/
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: yarn install --frozen-lockfile
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main')
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      NPM_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com/
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn semantic-release
